app/Http/routes.php
<?php
use Telegram\Bot\Api;
Route::group(['middleware' => ['web']], function () {

    // Home

    Route::get('/', 'Auth\AuthController@getLogin');
    Route::post('/', 'Auth\AuthController@postLogin');

    /* Route::get('/', [
      'uses' => 'HomeController@index',
      'as' => 'home'
      ]); */
    Route::get('language/{lang}', 'HomeController@language')->where('lang', '[A-Za-z_-]+');


    // Admin
    Route::get('admin', [
        'uses' => 'AdminController@admin',
        'as' => 'admin',
        'middleware' => 'admin'
    ]);
    Route::get('dashboard', 'DashboardController@index');
    Route::post('dashboard/getcharts', 'DashboardController@getcharts');
    Route::post('dashboard/sendmessage', 'DashboardController@sendmessage');
    Route::post('dashboard/sendbotmessage', 'DashboardController@sendbotmessage');


    // Blog
    // Contact
    Route::resource('contact', 'ContactController', [
        'except' => ['show', 'edit']
    ]);


    // User
    //Route::get('auth/login', 'Auth\AuthController@getLogin');
    //Route::post('auth/login', 'Auth\AuthController@postLogin');
    Route::get('user/sort/{role}', 'UserController@indexSort');

    Route::get('user/roles', 'UserController@getRoles');
    Route::post('user/roles', 'UserController@postRoles');

    Route::put('userseen/{user}', 'UserController@updateSeen');

    Route::post('front_user/update', 'FrontUserController@update');
    Route::get('front_user/change_password/{user_id}', 'FrontUserController@change_password');
    Route::post('front_user/change_password', 'FrontUserController@change_password');
    Route::resource('front_user', 'FrontUserController');
    
    Route::resource('messages', 'MessageController');
    Route::resource('recent_activity', 'RecentActivityController');

    Route::resource('user', 'UserController');

    Route::resource('plan', 'PlanController');
    
    Route::get('pages/detail/{pageid?}', 'PageController@detail');
    Route::resource('page', 'PageController');
    Route::resource('emailtemplate', 'EmailtemplateController');
	
	Route::resource('setting','SettingController');

    Route::get('bot/userbot/{user_id?}', 'BotController@userbot');
    Route::get('bot/bot_detail/{bot_id?}', 'BotController@admin_bot_detail');
    Route::get('bot/contactform_ques/{contact_form_id?}', 'BotController@contactform_ques');
    Route::get('bot/gallery_img/{gallery_id?}', 'BotController@gallery_img');
    Route::get('bot/detail/{botid?}', 'BotController@detail');
    Route::post('bot/setweb_hook', 'BotController@setweb_hook');
    Route::get('bot/update_bot/{bot_id?}', 'BotController@edit_bot');
    Route::post('bot/update_bot/{bot_id?}', 'BotController@update_bot');
    
    Route::resource('bot', 'BotController');

    Route::post('command/create/{bot_id?}', 'CommandController@create');
    Route::get('command/create/{bot_id?}', 'CommandController@create');
    
    Route::post('command/autoresponse_edit/{auto_id?}', 'CommandController@autoresponse_update');
    Route::get('command/autoresponse_edit/{auto_id?}', 'CommandController@autoresponse_edit');
    
    Route::post('command/chanel_edit/{chanel_id?}', 'CommandController@chanel_update');
    Route::get('command/chanel_edit/{chanel_id?}', 'CommandController@chanel_edit');
    
    Route::post('command/contactform_edit/{contactform_id?}', 'CommandController@contactform_update');
    Route::get('command/contactform_edit/{contactform_id?}', 'CommandController@contactform_edit');
    
    Route::post('command/gallery_edit/{contactform_id?}', 'CommandController@gallery_update');
    Route::get('command/gallery_edit/{contactform_id?}', 'CommandController@gallery_edit');
    
    Route::resource('command/upload', 'CommandController@imgupload');
    Route::resource('command', 'CommandController');

    // Routes for mychannel Controller

    Route::get('my_channel/detail/{cahnelId?}', 'MyChannelController@detail');
    Route::get('my_channel/update_channel/{cahnelId?}', 'MyChannelController@edit_channel');
    Route::post('my_channel/update_channel/{cahnelId?}', 'MyChannelController@update_channel');
    Route::resource('my_channel', 'MyChannelController');
    // End


    Route::get('/bot/get_state/{country_id?}', function(Request $request, $country_id) {
        $state = DB::table('countries')->get();

        $states = DB::table('states')
                ->where('country_id', '=', $country_id)
                ->get();

        $stateHtml = '';
        $stateHtml .= '<select id="state" name="state" class="form-control">';
        $stateHtml .= '<option value="">Select State</option>';
        if (!empty($states)) {
            foreach ($states as $k1 => $v1) {
                $stateHtml .= '<option value="' . $v1->id . '">' . $v1->name . '</option>';
            }
        }
        $stateHtml .= '</select>';

        echo $stateHtml;
        die;
    });

    // Authentication routes...

    Route::get('auth/logout', 'Auth\AuthController@getLogout');
    Route::get('auth/confirm/{token}', 'Auth\AuthController@getConfirm');

    // Resend routes...
    Route::get('auth/resend', 'Auth\AuthController@getResend');

    // Registration routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister');
    Route::post('auth/register', 'Auth\AuthController@postRegister');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail');
    Route::post('password/email', 'Auth\PasswordController@postEmail');

    // Password reset routes...
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
    Route::post('password/reset', 'Auth\PasswordController@postReset');
});

Route::get('/user_images/{size}/{name}', function($size = NULL, $name = NULL) {

    if (!is_null($size) && !is_null($name)) {
        $size = explode('x', $size);
        $cache_image = Image::cache(function($image) use($size, $name) {
                    return $image->make(url('/user_images/' . $name))->resize($size[0], $size[1]);
                }, 10); // cache for 10 minutes


        return Response::make($cache_image, 200, ['Content-Type' => 'image']);
    } else {
        abort(404);
    }
});


Route::post('/{bottoken}/webhook', function ($token) {
    
    $update = Telegram::commandsHandler(true);
    
    $data = json_decode($update,true);
    $messageText = (isset($data['message']['text']) && !empty($data['message']['text']))?$data['message']['text']:'';
    
    file_put_contents(public_path().'/updates.txt',$update.'>>'.$token);
    
    $telegram = new Api($token);
    $response = $telegram->getMe();
    
	$botId = $response->getId();
    $chatId = $data['message']['chat']['id'];
    $message_id = $data['message']['message_id'];
    
    $bot_data = DB::table('bots')->where('bot_token', 'LIKE', '%'.$token.'%')->get();
    $dbBotId = (isset($bot_data[0]->id) && $bot_data[0]->id!='')?$bot_data[0]->id:'';
    
    /* Add bot user */
    $from_id = $data['message']['from']['id'];
    $first_name = $data['message']['from']['first_name'];
    $last_name = $data['message']['from']['last_name'];
    
    $bot_user = DB::table('bot_users')
                    ->where('bot_id', '=', $dbBotId)
                    ->where('first_name', 'LIKE', $first_name)
                    ->get();
    
    $bot_user_id = '';
    if(isset($bot_user[0]->id) && !empty($bot_user[0]->id)){
        $bot_user_id = $bot_user[0]->id;
    }
    else{
        $bot_user_id = DB::table('bot_users')->insertGetId(
                ['bot_id' => $dbBotId, 'first_name' => $first_name, 'last_name' => $last_name, 'username' => '', 'fromid' => $from_id, 'created_at' => date('Y-m-d h:i:s'), 'modified_at' => date('Y-m-d h:i:s')]
            );
        
        //file_put_contents(public_path().'/result.txt',$bot_user_id);
    }
    /*******************************************************/
    
    
    
    /* Bot Message */
    if(!empty($bot_user_id)){
        
        //$date = $data['message']['date'];
        $bot_msg_date = date('Y-m-d h:i:s');
        
        $bot_messages_id = DB::table('bot_messages')->insertGetId(
                ['bot_id' => $dbBotId,'bot_user_id' => $bot_user_id,'date' => $bot_msg_date,'forward_from' => $from_id, 'forward_from_chat' => $chatId, 'forward_date' => $bot_msg_date, 'reply_to_chat' => '', 'reply_to_message' => '', 'text' => $messageText]
            );
    }    
    /*******************************************************/
    
    
    
    /*
    DB::table('tmp_bots')->insert(
        ['data_value' => serialize($bot_data)]
    );
    */
    
    
    
    
    if(!empty($dbBotId)){
        
        $autoresponse = '';
        if(isset($bot_data[0]->autoresponse) && !empty($bot_data[0]->autoresponse)){
            $autoresponse = $bot_data[0]->autoresponse;
        }
        
        $contact_form = '';
        if(isset($bot_data[0]->contact_form) && !empty($bot_data[0]->contact_form)){
            $contact_form = $bot_data[0]->contact_form;
        }
        
        $galleries = '';
        if(isset($bot_data[0]->galleries) && !empty($bot_data[0]->galleries)){
            $galleries = $bot_data[0]->galleries;
        }
        
        $channels = '';
        if(isset($bot_data[0]->channels) && !empty($bot_data[0]->channels)){
            $channels = $bot_data[0]->channels;
        }
        
        $array = array(
                '0' => $autoresponse,
                '1' => $contact_form,
                '2' => $galleries,
                '3' => $channels
        );
        
        $ke_arr = '';
        for($i = 0; $i<=3;$i++){
            if(isset($array[$i]) && !empty($array[$i])){
                $ke_arr[$i] = $array[$i];
            }
        }

        $ke_arr = array_chunk($ke_arr,2);
        $keyboard = $ke_arr;
		$msg = (isset($bot_data[0]->start_message) && !empty($bot_data[0]->start_message))?$bot_data[0]->start_message:'';
        

app/Models/MyChannel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MyChannel extends Model {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'my_channels';

    /**
     * One to Many relation
     *
     * @return Illuminate\Database\Eloquent\Relations\hasMany
     */


}

resources/views/front/mychannel/detail.blade.php
@extends('front.template')
@section('main')

<!-- http://jlinn.github.io/stripe-api-php/api/subscriptions.html -->


<div class="col-sm-8 col-sm-offset-4 col-lg-9 col-lg-offset-3">

    @include('front.top')

    <div class="my_account">
        <h4 class="left">{!! $chanels[0]->name !!}</h4>
        <a href="{!! URL::to('/my_channel/update_channel/'.$chanels[0]->id) !!}" class="btn btn-primary right">{!! trans('front/dashboard.edit_channel') !!}</a>
        <div class="clear"></div>
    </div>

    <div class="buying">
        <div class="create_bot">
            <div class="crete_bot_form">
                <ul>
                    <li>
                        <span>{{ trans('front/MyChannel.name') }}</span>
                        <label id="chanel_name">{!! $chanels[0]->name !!}</label>
                    </li>



                    <li>
                        <span>{{ trans('front/MyChannel.description') }}</span>
                        <label id="channel_description">{!! $chanels[0]->description !!}</label>
                    </li>

                    <li>
                        <span>{{ trans('front/MyChannel.share_link') }}</span>
                        <label id="channel_share_link">{!! $chanels[0]->share_link !!}</label>
                    </li>


                </ul>
            </div>
        </div>
    </div>
    
    <div class="col-lg-12">
         <div class="col-plan">
          <h2>{{ trans('front/MyChannel.messages_activity') }}</h2>
          <table>
            <thead>
              <tr>
                <th>{{ trans('front/MyChannel.channel_name') }}</th>
                <th>{{ trans('front/MyChannel.send_message') }} </th>
                <th>{{ trans('front/MyChannel.send_date') }} </th>
              </tr>
            </thead>
            <tbody>
              <?php
                if(!empty($chanelMesg)){
                  foreach($chanelMesg as $d2 => $v2){
                    ?>
                        <tr>
                          <td><?php echo $v2->channel_name;?></td>
                          <td><?php echo $v2->message;?></td>
                          <td><?php echo $v2->send_date;?></td>
                        </tr>
                    <?php
                  }
                }
                else{
                  ?>
                    <tr>
                      <td colspan="5">{{ trans('front/MyChannel.no_record') }}</td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
          </table>
        </div>
    </div>


</div>

<style>
    .thumb {
        width: 20%;
    }
</style>
@stop

resources/views/front/mychannel/edit.blade.php
@extends('back.template')

@section('main')

	<!-- Entête de page -->
	@include('back.partials.entete', ['title' => trans('back/plans.dashboard'), 'icone' => 'user', 'fil' => link_to('plan', trans('back/plans.Plans')) . ' / ' . trans('back/plans.edition')])

	<div class="col-sm-12">
		{!! Form::model($plan, ['route' => ['plan.update', $plan->id], 'method' => 'put', 'class' => 'form-horizontal panel',"enctype"=>"multipart/form-data"]) !!}
			{!! Form::control('text', 0, 'name', $errors, trans('back/plans.name')) !!}
			{!! Form::control('textarea', 0, 'description', $errors, trans('back/plans.description')) !!}
			{!! Form::control('text', 0, 'duration', $errors, trans('back/plans.duration')) !!}
			{!! Form::control('text', 0, 'price', $errors, trans('back/plans.price')) !!}
			{!! Form::control('text', 0, 'autoresponses', $errors, trans('back/plans.autoresponses')) !!}
			{!! Form::control('text', 0, 'contact_forms', $errors, trans('back/plans.contact_forms')) !!}
			{!! Form::control('text', 0, 'image_gallery', $errors, trans('back/plans.image_gallery')) !!}
			{!! Form::control('text', 0, 'gallery_images', $errors, trans('back/plans.gallery_images')) !!}
			{!! Form::control('text', 0, 'manual_message', $errors, trans('back/plans.manual_message')) !!}
			{!! Form::checkBoxNew('custom_image', trans('back/plans.custom_image'),1,$plan->custom_image) !!}
			{!! Form::checkBoxNew('custom_welcome_message', trans('back/plans.custom_welcome_message'),1,$plan->custom_welcome_message) !!}
			{!! Form::checkBoxNew('custom_not_allowed_message', trans('back/plans.custom_not_allowed_message'),1,$plan->custom_not_allowed_message) !!}
			{!! Form::checkBoxNew('status', trans('back/plans.status'),1,$plan->status) !!}
			
			{!! Form::submit(trans('front/form.send')) !!}
		{!! Form::close() !!}
	</div>

@stop

resources/views/front/mychannel/edit_channel.blade.php
@extends('front.template')
@section('main')


<div class="col-sm-8 col-sm-offset-4 col-lg-9 col-lg-offset-3">

    @include('front.top')  

    {!! Form::open(['url' => 'my_channel/update_channel/'.$channel->id, 'method' => 'post','enctype'=>"multipart/form-data", 'class' => 'form-horizontal panel','id' =>'payment-form']) !!}
    
    {!! Form::hidden('id', $channel->id, array('id' => 'bot')) !!}

    <div>
        <div class="my_account telegram">
            <h4>{!! HTML::image('img/front/telegrtam_icon.png') !!}<span>{{ trans('front/MyChannel.telegram') }}</span></h4>
            <h5>{{ trans('front/MyChannel.create') }}</h5>
        </div>

        <div class="buying">
            <div class="create_bot">
                <div class="crete_bot_form">
                    <ul>
                        <li>
                            <span>{{ trans('front/MyChannel.name') }} {!! HTML::image('img/front/icon.png') !!}</span>
                            <label id="uName">{!! Form::control('text', 0, 'name', $errors,'',$channel->name) !!}</label>
                        </li>

                        <li>
                            <span>{{ trans('front/MyChannel.description') }} {!! HTML::image('img/front/icon.png') !!}</span>
                            <label>{!! Form::control('textarea', 0, 'description', $errors,'',$channel->description) !!}</label>
                        </li>
                    </ul>
                </div>
                
                <div class="submit">
                  {!! Form::submit_new(trans('front/form.send')) !!}
                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}

</div>


@stop

resources/views/front/mychannel/index.blade.php
@extends('front.template')

@section('head')

<style type="text/css">
  
  .badge {
    padding: 1px 8px 1px;
    background-color: #aaa !important;
  }

</style>

@stop

@section('main')
   
   {!! link_to_route('bot.create', trans('front/bots.create'), [] ['class' => 'btn btn-success btn-block btn']) !!}
   
   @if(session()->has('ok'))
    @include('partials/error', ['type' => 'success', 'message' => session('ok')])
   @endif

  <div class="pull-right link">{!! $links !!}</div>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>{{ trans('front/bots.name') }}</th>
					<th>{{ trans('front/bots.bot_token') }}</th>
					<th>{{ trans('front/bots.start_message') }}</th>
					
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			  	@foreach ($bots as $bot)
		<tr>
			<td class="text-primary"><strong>{{ $bot->username }}</strong></td>
			
			<td>{{ $bot->duration }}</td>
			<td>{{ $bot->start_message }}</td>
			
			
			<td>{!! link_to_route('bot.edit', trans('front/bots.edit'), [$bot->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
			<td>
				{!! Form::open(['method' => 'DELETE', 'route' => ['bot.destroy', $bot->id]]) !!}
				{!! Form::destroy(trans('back/plans.destroy'), trans('front/bots.confirm')) !!}
				{!! Form::close() !!}
			</td>
		</tr>
	@endforeach
      </tbody>
		</table>
	</div>

	<div class="pull-right link">{!! $links !!}</div>

@stop

resources/views/front/mychannel/show.blade.php
@extends('back.template')

@section('main')

	@include('back.partials.entete', ['title' => trans('back/plans.dashboard'), 'icone' => 'user', 'fil' => link_to('plan', trans('back/plans.Plans')) . ' / ' . trans('back/plans.card')])

	<p>{{ trans('back/plans.name') . ' : ' .  $plan->name }}</p>
	<p>{{ trans('back/plans.description') . ' : ' .  $plan->description }}</p>
	<p>{{ trans('back/plans.duration') . ' : ' .  $plan->duration }}</p>
	<p>{{ trans('back/plans.price') . ' : ' .  $plan->price }}</p>
	<p>{{ trans('back/plans.autoresponses') . ' : ' .  $plan->autoresponses }}</p>
	<p>{{ trans('back/plans.contact_forms') . ' : ' .  $plan->contact_forms }}</p>
	<p>{{ trans('back/plans.image_gallery') . ' : ' .  $plan->image_gallery }}</p>
	<p>{{ trans('back/plans.gallery_images') . ' : ' .  $plan->gallery_images }}</p>
	<p>{{ trans('back/plans.manual_message') . ' : ' .  $plan->manual_message }}</p>
	
	<p>
	{{ trans('back/plans.custom_image') . ' : '}} 
	
	@if($plan->custom_image ==1) {{ trans('back/plans.yes')}}  @else {{ trans('back/plans.no')}}  @endif</p>
   
  <p>
	{{ trans('back/plans.custom_welcome_message') . ' : '}} 
	
	@if($plan->custom_welcome_message ==1) {{ trans('back/plans.yes')}}  @else {{ trans('back/plans.no')}}  @endif</p>
  
  <p>
	{{ trans('back/plans.custom_not_allowed_message') . ' : '}} 
	
	@if($plan->custom_not_allowed_message ==1) {{ trans('back/plans.yes')}}  @else {{ trans('back/plans.no')}}  @endif</p>

  <p>
  {{ trans('back/plans.status') . ' : '}} 
	 @if($plan->status ==1) <img class="img-responsive" src="{{asset("img/enable.png")}}" alt=""> @else <img class="img-responsive" src="{{asset("img/disable.png")}}" alt=""> @endif
  </p>
	
   
@stop

resources/views/front/mychannel/table.blade.php
	@foreach ($plans as $plan)
		<tr>
			<td class="text-primary"><strong>{{ $plan->name }}</strong></td>
			
			<td>{{ $plan->duration }}</td>
			<td>{{ $plan->price }}</td>
			<td>
			@if($plan->status ==1)
			 <img class="img-responsive" src="img/enable.png" alt="">
			@else
			 <img class="img-responsive" src="img/disable.png" alt="">
			@endif
			</td>
			<td>{!! link_to_route('plan.show', trans('back/plans.see'), [$plan->id], ['class' => 'btn btn-success btn-block btn']) !!}</td>
			<td>{!! link_to_route('plan.edit', trans('back/users.edit'), [$plan->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
			<td>
				{!! Form::open(['method' => 'DELETE', 'route' => ['plan.destroy', $plan->id]]) !!}
				{!! Form::destroy(trans('back/plans.destroy'), trans('back/plans.destroy-warning')) !!}
				{!! Form::close() !!}
			</td>
		</tr>
	@endforeach