app/Http/routes.php
<?php
use Telegram\Bot\Api;
Route::group(['middleware' => ['web']], function () {

    // Home

    Route::get('/', 'Auth\AuthController@getLogin');
    Route::post('/', 'Auth\AuthController@postLogin');

    /* Route::get('/', [
      'uses' => 'HomeController@index',
      'as' => 'home'
      ]); */
    Route::get('language/{lang}', 'HomeController@language')->where('lang', '[A-Za-z_-]+');


    // Admin
    Route::get('admin', [
        'uses' => 'AdminController@admin',
        'as' => 'admin',
        'middleware' => 'admin'
    ]);
    Route::get('dashboard', 'DashboardController@index');
    Route::post('dashboard/getcharts', 'DashboardController@getcharts');
    Route::post('dashboard/sendmessage', 'DashboardController@sendmessage');
    Route::post('dashboard/sendbotmessage', 'DashboardController@sendbotmessage');


    // Blog
    // Contact
    Route::resource('contact', 'ContactController', [
        'except' => ['show', 'edit']
    ]);


    // User
    //Route::get('auth/login', 'Auth\AuthController@getLogin');
    //Route::post('auth/login', 'Auth\AuthController@postLogin');
    Route::get('user/sort/{role}', 'UserController@indexSort');

    Route::get('user/roles', 'UserController@getRoles');
    Route::post('user/roles', 'UserController@postRoles');

    Route::put('userseen/{user}', 'UserController@updateSeen');

    Route::post('front_user/update', 'FrontUserController@update');
    Route::get('front_user/change_password/{user_id}', 'FrontUserController@change_password');
    Route::post('front_user/change_password', 'FrontUserController@change_password');
    Route::resource('front_user', 'FrontUserController');
    
    Route::resource('messages', 'MessageController');
    Route::resource('recent_activity', 'RecentActivityController');

    Route::resource('user', 'UserController');

    Route::resource('plan', 'PlanController');
    
    Route::get('pages/detail/{pageid?}', 'PageController@detail');
    Route::resource('page', 'PageController');
    Route::resource('emailtemplate', 'EmailtemplateController');
	
	Route::resource('setting','SettingController');

    Route::get('bot/userbot/{user_id?}', 'BotController@userbot');
    Route::get('bot/bot_detail/{bot_id?}', 'BotController@admin_bot_detail');
    Route::get('bot/contactform_ques/{contact_form_id?}', 'BotController@contactform_ques');
    Route::get('bot/gallery_img/{gallery_id?}', 'BotController@gallery_img');
    Route::get('bot/detail/{botid?}', 'BotController@detail');
    Route::post('bot/setweb_hook', 'BotController@setweb_hook');
    Route::get('bot/update_bot/{bot_id?}', 'BotController@edit_bot');
    Route::post('bot/update_bot/{bot_id?}', 'BotController@update_bot');
    
    Route::resource('bot', 'BotController');

    Route::post('command/create/{bot_id?}', 'CommandController@create');
    Route::get('command/create/{bot_id?}', 'CommandController@create');
    
    Route::post('command/autoresponse_edit/{auto_id?}', 'CommandController@autoresponse_update');
    Route::get('command/autoresponse_edit/{auto_id?}', 'CommandController@autoresponse_edit');
    
    Route::post('command/chanel_edit/{chanel_id?}', 'CommandController@chanel_update');
    Route::get('command/chanel_edit/{chanel_id?}', 'CommandController@chanel_edit');
    
    Route::post('command/contactform_edit/{contactform_id?}', 'CommandController@contactform_update');
    Route::get('command/contactform_edit/{contactform_id?}', 'CommandController@contactform_edit');
    
    Route::post('command/gallery_edit/{contactform_id?}', 'CommandController@gallery_update');
    Route::get('command/gallery_edit/{contactform_id?}', 'CommandController@gallery_edit');
    
    Route::resource('command/upload', 'CommandController@imgupload');
    Route::resource('command', 'CommandController');

    // Routes for mychannel Controller

    Route::get('my_channel/detail/{cahnelId?}', 'MyChannelController@detail');
    Route::get('my_channel/update_channel/{cahnelId?}', 'MyChannelController@edit_channel');
    Route::post('my_channel/update_channel/{cahnelId?}', 'MyChannelController@update_channel');
    Route::resource('my_channel', 'MyChannelController');
    // End


    Route::get('/bot/get_state/{country_id?}', function(Request $request, $country_id) {
        $state = DB::table('countries')->get();

        $states = DB::table('states')
                ->where('country_id', '=', $country_id)
                ->get();

        $stateHtml = '';
        $stateHtml .= '<select id="state" name="state" class="form-control">';
        $stateHtml .= '<option value="">Select State</option>';
        if (!empty($states)) {
            foreach ($states as $k1 => $v1) {
                $stateHtml .= '<option value="' . $v1->id . '">' . $v1->name . '</option>';
            }
        }
        $stateHtml .= '</select>';

        echo $stateHtml;
        die;
    });

    // Authentication routes...

    Route::get('auth/logout', 'Auth\AuthController@getLogout');
    Route::get('auth/confirm/{token}', 'Auth\AuthController@getConfirm');

    // Resend routes...
    Route::get('auth/resend', 'Auth\AuthController@getResend');

    // Registration routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister');
    Route::post('auth/register', 'Auth\AuthController@postRegister');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail');
    Route::post('password/email', 'Auth\PasswordController@postEmail');

    // Password reset routes...
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
    Route::post('password/reset', 'Auth\PasswordController@postReset');
});

Route::get('/user_images/{size}/{name}', function($size = NULL, $name = NULL) {

    if (!is_null($size) && !is_null($name)) {
        $size = explode('x', $size);
        $cache_image = Image::cache(function($image) use($size, $name) {
                    return $image->make(url('/user_images/' . $name))->resize($size[0], $size[1]);
                }, 10); // cache for 10 minutes


        return Response::make($cache_image, 200, ['Content-Type' => 'image']);
    } else {
        abort(404);
    }
});


Route::post('/{bottoken}/webhook', function ($token) {
    
    $update = Telegram::commandsHandler(true);
    
    $data = json_decode($update,true);
    $messageText = (isset($data['message']['text']) && !empty($data['message']['text']))?$data['message']['text']:'';
    
    file_put_contents(public_path().'/updates.txt',$update.'>>'.$token);
    
    $telegram = new Api($token);
    $response = $telegram->getMe();
    
	$botId = $response->getId();
    $chatId = $data['message']['chat']['id'];
    $message_id = $data['message']['message_id'];
    
    $bot_data = DB::table('bots')->where('bot_token', 'LIKE', '%'.$token.'%')->get();
    $dbBotId = (isset($bot_data[0]->id) && $bot_data[0]->id!='')?$bot_data[0]->id:'';
    
    /* Add bot user */
    $from_id = $data['message']['from']['id'];
    $first_name = $data['message']['from']['first_name'];
    $last_name = $data['message']['from']['last_name'];
    
    $bot_user = DB::table('bot_users')
                    ->where('bot_id', '=', $dbBotId)
                    ->where('first_name', 'LIKE', $first_name)
                    ->get();
    
    $bot_user_id = '';
    if(isset($bot_user[0]->id) && !empty($bot_user[0]->id)){
        $bot_user_id = $bot_user[0]->id;
    }
    else{
        $bot_user_id = DB::table('bot_users')->insertGetId(
                ['bot_id' => $dbBotId, 'first_name' => $first_name, 'last_name' => $last_name, 'username' => '', 'fromid' => $from_id, 'created_at' => date('Y-m-d h:i:s'), 'modified_at' => date('Y-m-d h:i:s')]
            );
        
        //file_put_contents(public_path().'/result.txt',$bot_user_id);
    }
    /*******************************************************/
    
    
    
    /* Bot Message */
    if(!empty($bot_user_id)){
        
        //$date = $data['message']['date'];
        $bot_msg_date = date('Y-m-d h:i:s');
        
        $bot_messages_id = DB::table('bot_messages')->insertGetId(
                ['bot_id' => $dbBotId,'bot_user_id' => $bot_user_id,'date' => $bot_msg_date,'forward_from' => $from_id, 'forward_from_chat' => $chatId, 'forward_date' => $bot_msg_date, 'reply_to_chat' => '', 'reply_to_message' => '', 'text' => $messageText]
            );
    }    
    /*******************************************************/
    
    
    
    /*
    DB::table('tmp_bots')->insert(
        ['data_value' => serialize($bot_data)]
    );
    */
    
    
    
    
    if(!empty($dbBotId)){
        
        $autoresponse = '';
        if(isset($bot_data[0]->autoresponse) && !empty($bot_data[0]->autoresponse)){
            $autoresponse = $bot_data[0]->autoresponse;
        }
        
        $contact_form = '';
        if(isset($bot_data[0]->contact_form) && !empty($bot_data[0]->contact_form)){
            $contact_form = $bot_data[0]->contact_form;
        }
        
        $galleries = '';
        if(isset($bot_data[0]->galleries) && !empty($bot_data[0]->galleries)){
            $galleries = $bot_data[0]->galleries;
        }
        
        $channels = '';
        if(isset($bot_data[0]->channels) && !empty($bot_data[0]->channels)){
            $channels = $bot_data[0]->channels;
        }
        
        $array = array(
                '0' => $autoresponse,
                '1' => $contact_form,
                '2' => $galleries,
                '3' => $channels
        );
        
        $ke_arr = '';
        for($i = 0; $i<=3;$i++){
            if(isset($array[$i]) && !empty($array[$i])){
                $ke_arr[$i] = $array[$i];
            }
        }

        $ke_arr = array_chunk($ke_arr,2);
        $keyboard = $ke_arr;
		$msg = (isset($bot_data[0]->start_message) && !empty($bot_data[0]->start_message))?$bot_data[0]->start_message:'';
        

app/Models/User.php
<?php namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	/**
	 * One to Many relation
	 *
	 * @return Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function role() 
	{
		return $this->belongsTo('App\Models\Role');
	}
	
	public function country() 
	{
		return $this->belongsTo('App\Models\Country');
	}

	/**
	 * One to Many relation
	 *
	 * @return Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function user_billings() 
	{
	  return $this->hasMany('App\Models\UserBilling');
	}
	/**
	 * One to Many relation
	 *
	 * @return Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function user_subscriptions() 
	{
	  return $this->hasMany('App\Models\UserSubscription');
	}
	/**
	 * One to Many relation
	 *
	 * @return Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function user_transactions() 
	{
	  return $this->hasMany('App\Models\UserTransaction');
	}

	

	/**
	 * Check media all access
	 *
	 * @return bool
	 */
	public function accessMediasAll()
	{
	    return $this->role->slug == 'admin';
	}

	/**
	 * Check media access one folder
	 *
	 * @return bool
	 */
	public function accessMediasFolder()
	{
	    return $this->role->slug = 'user';
	}

}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['first_name','last_name', 'email', 'password','mobile'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use App\Repositories\UserBillingRepository;
use App\Repositories\RoleRepository;
use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Requests\RoleRequest;
use App\Models\User;
use App\Models\UserSubscription;
use App\Models\UserTransaction;
use App\Models\Country;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class UserController extends Controller {

	/**
	 * The UserRepository instance.
	 *
	 * @var App\Repositories\UserRepository
	 */
	protected $user_gestion;

	/**
	 * The RoleRepository instance.
	 *
	 * @var App\Repositories\RoleRepository
	 */	
	protected $role_gestion;
	
	protected $userbilling_gestion;

	/**
	 * Create a new UserController instance.
	 *
	 * @param  App\Repositories\UserRepository $user_gestion
	 * @param  App\Repositories\RoleRepository $role_gestion
	 * @return void
	 */
	public function __construct(
		UserRepository $user_gestion,
		RoleRepository $role_gestion,
		UserBillingRepository $userbilling_gestion)
	{
	
		$this->user_gestion = $user_gestion;
		$this->role_gestion = $role_gestion;
		$this->userbilling_gestion = $userbilling_gestion;
       
		$this->middleware('user', ['except' => ['index', 'show', 'indexSort', 'create','store','edit','update','destroy','getRoles','postRoles']]);
		
	
		$this->middleware('admin');
		
		$this->middleware('ajax', ['only' => 'updateSeen']);
	}
	
	public function dashboard()
	{
	     echo 'as';
	exit;
		return view('back.users.index');	
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return $this->indexSort('total');
	}

	/**
	 * Display a listing of the resource.
	 *
     * @param  string  $role
	 * @return Response
	 */
	public function indexSort($role)
	{
		$counts = $this->user_gestion->counts();
		$users = $this->user_gestion->index(4, $role);
		
		$links = $users->render();
		$roles = $this->role_gestion->all();

		return view('back.users.index', compact('users', 'links', 'counts', 'roles'));		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('back.users.create', $this->role_gestion->getAllSelect());
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  App\requests\UserCreateRequest $request
	 *
	 * @return Response
	 */
	public function store(
		UserCreateRequest $request)
	{
		$this->user_gestion->store($request->all());

		return redirect('user')->with('ok', trans('back/users.created'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  App\Models\User
	 * @return Response
	 */
	public function show(User $user)
	{
	   
		$user_billings = $this->userbilling_gestion->all($user->id);
		
		$user_subscriptions = UserSubscription::with('plan')->where('user_id', $user->id)->get();
		
		$user_transactions = UserTransaction::with('plan')->where('user_id', $user->id)->get();
	
		return view('back.users.show',  compact('user','user_billings','user_subscriptions','user_transactions'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  App\Models\User
	 * @return Response
	 */
	public function edit(User $user)
	{
	   
		$country = Country::all()->pluck('name', 'id');
		
		return view('back.users.edit', array_merge(compact('user','country'), $this->role_gestion->getAllSelect()));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  App\requests\UserUpdateRequest $request
	 * @param  App\Models\User
	 * @return Response
	 */
	public function update(
		UserUpdateRequest $request,
		User $user)
	{
	    if($request->hasFile('image'))
		{
			
			$error =$_FILES["image"]["error"];
			
			$file = Input::file('image');
            //getting timestamp
			$ext=@end(@explode(".",$file->getClientOriginalName()));
			
            $name = time().".".$ext;
          
            $file->move(public_path().'/user_images/', $name);
		    $user->image=$name;
		 }
		 
	
		$this->user_gestion->update($request->all(), $user);

		return redirect('user')->with('ok', trans('back/users.updated'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  Illuminate\Http\Request $request
	 * @param  App\Models\User $user
	 * @return Response
	 */
	public function updateSeen(
		Request $request, 
		User $user)
	{
		$this->user_gestion->update($request->all(), $user);

		return response()->json();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  App\Models\user $user
	 * @return Response
	 */
	public function destroy(User $user)
	{
		$this->user_gestion->destroyUser($user);

		return redirect('user')->with('ok', trans('back/users.destroyed'));
	}

	/**
	 * Display the roles form
	 *
	 * @return Response
	 */
	public function getRoles()
	{
		$roles = $this->role_gestion->all();

		return view('back.users.roles', compact('roles'));
	}

	/**
	 * Update roles
	 *
	 * @param  App\requests\RoleRequest $request
	 * @return Response
	 */
	public function postRoles(RoleRequest $request)
	{
		$this->role_gestion->update($request->except('_token'));
		
		return redirect('user/roles')->with('ok', trans('back/roles.ok'));
	}
	
}

resources/views/back/users/create.blade.php
@extends('back.template')

@section('main')

 <!-- Entête de page -->
  @include('back.partials.entete', ['title' => trans('back/users.dashboard'), 'icone' => 'user', 'fil' => link_to('user', trans('back/users.Users')) . ' / ' . trans('back/users.creation')])

	<div class="col-sm-12">
		{!! Form::open(['url' => 'user', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}	
			<?php /*?>{!! Form::control('text', 0, 'username', $errors, trans('back/users.name')) !!}<?php */?>
			{!! Form::control('email', 0, 'email', $errors, trans('back/users.email')) !!}
			{!! Form::control('password', 0, 'password', $errors, trans('back/users.password')) !!}
			{!! Form::control('password', 0, 'password_confirmation', $errors, trans('back/users.confirm-password')) !!}
			{!! Form::selection('role', $select, null, trans('back/users.role')) !!}
			{!! Form::submit(trans('front/form.send')) !!}
		{!! Form::close() !!}
	</div>

@stop

resources/views/back/users/edit.blade.php
@extends('back.template')

@section('main')

	<!-- Entête de page -->
	@include('back.partials.entete', ['title' => trans('back/users.dashboard'), 'icone' => 'user', 'fil' => link_to('user', trans('back/users.Users')) . ' / ' . trans('back/users.edition')])

	<div class="col-sm-12">
		{!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put', 'class' => 'form-horizontal panel',"enctype"=>"multipart/form-data"]) !!}
			{!! Form::control('text', 0, 'first_name', $errors, trans('back/users.first_name')) !!}
			{!! Form::control('text', 0, 'last_name', $errors, trans('back/users.last_name')) !!}
			{!! Form::control('email', 0, 'email', $errors, trans('back/users.email')) !!}
			{!! Form::selection('role', $select, $user->role_id, trans('back/users.role')) !!}
			{!! Form::selection('country', $country, $user->country_id, trans('back/users.country')) !!}
			{!! Form::control('text', 0, 'zipcode', $errors, trans('back/users.zipcode')) !!}
			{!! Form::control('text', 0, 'mobile', $errors, trans('back/users.mobile')) !!}
			{!! Form::selection('user_type', array("individual"=>"individual","company"=>"company"), $user->user_type, trans('back/users.user_type'),array('class' => 'form-control','onchange'=>'checkUserType(this.value);')) !!}
			<div class="company_div" style="display:none;">
			{!! Form::control('text',0,'company_name', $errors, trans('back/users.company_name')) !!}
			{!! Form::control('text',0,'vat_number', $errors,  trans('back/users.vat_number')) !!}
			</div>
			{!! Form::selection('payment_method', array("stripe"=>"stripe"), $user->payment_method, trans('back/users.payment_method')) !!}
			{!! Form::control('file', 0, 'image', $errors, trans('back/users.image')) !!}
			
			@if($user->image !='')
			 <img class="img-responsive" src="{{ url('/user_images/150x150/'.$user->image) }}" alt="">
			@endif
			
			{!! Form::checkHorizontal('status', trans('back/users.status'), $user->status) !!}
			{!! Form::submit(trans('front/form.send')) !!}
		{!! Form::close() !!}
	</div>

@stop
@section('scripts')
<script type="text/javascript">
function checkUserType(value){
  if(value=='individual'){
   jQuery('.company_div').hide();
  }else{
   jQuery('.company_div').show();
  }
}
@if($user->user_type =='company')
 jQuery('.company_div').show();
@endif
</script>
@stop

resources/views/back/users/index.blade.php
@extends('back.template')

@section('head')

<style type="text/css">
  
  .badge {
    padding: 1px 8px 1px;
    background-color: #aaa !important;
  }

</style>

@stop

@section('main')

  @include('back.partials.entete', ['title' => trans('back/users.dashboard') . link_to_route('user.create', trans('back/users.add'), [], ['class' => 'btn btn-info pull-right']), 'icone' => 'user', 'fil' => trans('back/users.users')])
 
  <div id="tri" class="btn-group btn-group-sm">
    <a href="{!! url('user') !!}" type="button" name="total" class="btn btn-default {{ classActiveOnlyPath('user') }}">{{ trans('back/users.all') }} 
      <span class="badge">{{  $counts['total'] }}</span>
    </a>
    @foreach ($roles as $role)
      <a href="{!! url('user/sort/' . $role->slug) !!}" type="button" name="{!! $role->slug !!}" class="btn btn-default {{ classActiveOnlySegment(3, $role->slug) }}">{{ $role->title . 's' }} 
        <span class="badge">{{ $counts[$role->slug] }}</span>
      </a>
    @endforeach
  </div>

	@if(session()->has('ok'))
    @include('partials/error', ['type' => 'success', 'message' => session('ok')])
	@endif

  <div class="pull-right link">{!! $links !!}</div>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>{{ trans('back/users.name') }}</th>
					<th>{{ trans('back/users.email') }}</th>
					<th>{{ trans('back/users.role') }}</th>
					<th>{{ trans('back/users.status') }}</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			  @include('back.users.table')
      </tbody>
		</table>
	</div>

	<div class="pull-right link">{!! $links !!}</div>

@stop

@section('scripts')

  <script>
    
    $(function() {

      // Seen gestion
      $(document).on('change', ':checkbox', function() {    
        $(this).parents('tr').toggleClass('warning');
        $(this).hide().parent().append('<i class="fa fa-refresh fa-spin"></i>');
        var token = $('input[name="_token"]').val();
        $.ajax({
          url: '{!! url('userseen') !!}' + '/' + this.value,
          type: 'PUT',
          data: "seen=" + this.checked + "&_token=" + token
        })
        .done(function() {
          $('.fa-spin').remove();
          $('input[type="checkbox"]:hidden').show();
        })
        .fail(function() {
          $('.fa-spin').remove();
          var chk = $('input[type="checkbox"]:hidden');
          chk.show().prop('checked', chk.is(':checked') ? null:'checked').parents('tr').toggleClass('warning');
          alert('{{ trans('back/users.fail') }}');
        });
      });

    });

  </script>

@stop

resources/views/back/users/roles.blade.php
@extends('back.template')

@section('main')

  @include('back.partials.entete', ['title' => trans('back/roles.dashboard'), 'icone' => 'user', 'fil' => link_to('user', trans('back/users.Users')) . ' / ' . trans('back/roles.roles')])

	<div class="col-sm-12">
		@if(session()->has('ok'))
			@include('partials/error', ['type' => 'success', 'message' => session('ok')])
		@endif
		{!! Form::open(['url' => 'user/roles', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}	
			@foreach ($roles as $role) 
				{!! Form::control('text', 0, $role->slug, $errors, trans('back/roles.' . $role->slug), $role->title) !!}
			@endforeach
			{!! Form::submit(trans('front/form.send')) !!}
		{!! Form::close() !!}
	</div>

@stop

resources/views/back/users/table.blade.php
	@foreach ($users as $user)
		<tr {!! !$user->status? 'class="warning"' : '' !!}>
			<td class="text-primary"><strong>{{ $user->first_name }}</strong></td>
			
			<td>{{ $user->email }}</td>
			<td>{{ $user->role->title }}</td>
			<td>
			@if($user->status ==1)
			 <img class="img-responsive" src="img/enable.png" alt="">
			@else
			 <img class="img-responsive" src="img/disable.png" alt="">
			@endif
			</td>
			<td><a class="btn btn-success btn-block btn" href="{!! URL::to('bot/userbot/'.$user->id) !!}">{!! trans('back/users.bot') !!}</a></td>
			<td>{!! link_to_route('user.show', trans('back/users.see'), [$user->id], ['class' => 'btn btn-success btn-block btn']) !!}</td>
			<td>{!! link_to_route('user.edit', trans('back/users.edit'), [$user->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
			<td>
				{!! Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) !!}
				{!! Form::destroy(trans('back/users.destroy'), trans('back/users.destroy-warning')) !!}
				{!! Form::close() !!}
			</td>
		</tr>
	@endforeach