app/Http/routes.php
<?php
use Telegram\Bot\Api;
Route::group(['middleware' => ['web']], function () {

    // Home

    Route::get('/', 'Auth\AuthController@getLogin');
    Route::post('/', 'Auth\AuthController@postLogin');

    /* Route::get('/', [
      'uses' => 'HomeController@index',
      'as' => 'home'
      ]); */
    Route::get('language/{lang}', 'HomeController@language')->where('lang', '[A-Za-z_-]+');


    // Admin
    Route::get('admin', [
        'uses' => 'AdminController@admin',
        'as' => 'admin',
        'middleware' => 'admin'
    ]);
    Route::get('dashboard', 'DashboardController@index');
    Route::post('dashboard/getcharts', 'DashboardController@getcharts');
    Route::post('dashboard/sendmessage', 'DashboardController@sendmessage');
    Route::post('dashboard/sendbotmessage', 'DashboardController@sendbotmessage');


    // Blog
    // Contact
    Route::resource('contact', 'ContactController', [
        'except' => ['show', 'edit']
    ]);


    // User
    //Route::get('auth/login', 'Auth\AuthController@getLogin');
    //Route::post('auth/login', 'Auth\AuthController@postLogin');
    Route::get('user/sort/{role}', 'UserController@indexSort');

    Route::get('user/roles', 'UserController@getRoles');
    Route::post('user/roles', 'UserController@postRoles');

    Route::put('userseen/{user}', 'UserController@updateSeen');

    Route::post('front_user/update', 'FrontUserController@update');
    Route::get('front_user/change_password/{user_id}', 'FrontUserController@change_password');
    Route::post('front_user/change_password', 'FrontUserController@change_password');
    Route::resource('front_user', 'FrontUserController');
    
    Route::resource('messages', 'MessageController');
    Route::resource('recent_activity', 'RecentActivityController');

    Route::resource('user', 'UserController');

    Route::resource('plan', 'PlanController');
    
    Route::get('pages/detail/{pageid?}', 'PageController@detail');
    Route::resource('page', 'PageController');
    Route::resource('emailtemplate', 'EmailtemplateController');
	
	Route::resource('setting','SettingController');

    Route::get('bot/userbot/{user_id?}', 'BotController@userbot');
    Route::get('bot/bot_detail/{bot_id?}', 'BotController@admin_bot_detail');
    Route::get('bot/contactform_ques/{contact_form_id?}', 'BotController@contactform_ques');
    Route::get('bot/gallery_img/{gallery_id?}', 'BotController@gallery_img');
    Route::get('bot/detail/{botid?}', 'BotController@detail');
    Route::post('bot/setweb_hook', 'BotController@setweb_hook');
    Route::get('bot/update_bot/{bot_id?}', 'BotController@edit_bot');
    Route::post('bot/update_bot/{bot_id?}', 'BotController@update_bot');
    
    Route::resource('bot', 'BotController');

    Route::post('command/create/{bot_id?}', 'CommandController@create');
    Route::get('command/create/{bot_id?}', 'CommandController@create');
    
    Route::post('command/autoresponse_edit/{auto_id?}', 'CommandController@autoresponse_update');
    Route::get('command/autoresponse_edit/{auto_id?}', 'CommandController@autoresponse_edit');
    
    Route::post('command/chanel_edit/{chanel_id?}', 'CommandController@chanel_update');
    Route::get('command/chanel_edit/{chanel_id?}', 'CommandController@chanel_edit');
    
    Route::post('command/contactform_edit/{contactform_id?}', 'CommandController@contactform_update');
    Route::get('command/contactform_edit/{contactform_id?}', 'CommandController@contactform_edit');
    
    Route::post('command/gallery_edit/{contactform_id?}', 'CommandController@gallery_update');
    Route::get('command/gallery_edit/{contactform_id?}', 'CommandController@gallery_edit');
    
    Route::resource('command/upload', 'CommandController@imgupload');
    Route::resource('command', 'CommandController');

    // Routes for mychannel Controller

    Route::get('my_channel/detail/{cahnelId?}', 'MyChannelController@detail');
    Route::get('my_channel/update_channel/{cahnelId?}', 'MyChannelController@edit_channel');
    Route::post('my_channel/update_channel/{cahnelId?}', 'MyChannelController@update_channel');
    Route::resource('my_channel', 'MyChannelController');
    // End


    Route::get('/bot/get_state/{country_id?}', function(Request $request, $country_id) {
        $state = DB::table('countries')->get();

        $states = DB::table('states')
                ->where('country_id', '=', $country_id)
                ->get();

        $stateHtml = '';
        $stateHtml .= '<select id="state" name="state" class="form-control">';
        $stateHtml .= '<option value="">Select State</option>';
        if (!empty($states)) {
            foreach ($states as $k1 => $v1) {
                $stateHtml .= '<option value="' . $v1->id . '">' . $v1->name . '</option>';
            }
        }
        $stateHtml .= '</select>';

        echo $stateHtml;
        die;
    });

    // Authentication routes...

    Route::get('auth/logout', 'Auth\AuthController@getLogout');
    Route::get('auth/confirm/{token}', 'Auth\AuthController@getConfirm');

    // Resend routes...
    Route::get('auth/resend', 'Auth\AuthController@getResend');

    // Registration routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister');
    Route::post('auth/register', 'Auth\AuthController@postRegister');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail');
    Route::post('password/email', 'Auth\PasswordController@postEmail');

    // Password reset routes...
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
    Route::post('password/reset', 'Auth\PasswordController@postReset');
});

Route::get('/user_images/{size}/{name}', function($size = NULL, $name = NULL) {

    if (!is_null($size) && !is_null($name)) {
        $size = explode('x', $size);
        $cache_image = Image::cache(function($image) use($size, $name) {
                    return $image->make(url('/user_images/' . $name))->resize($size[0], $size[1]);
                }, 10); // cache for 10 minutes


        return Response::make($cache_image, 200, ['Content-Type' => 'image']);
    } else {
        abort(404);
    }
});


Route::post('/{bottoken}/webhook', function ($token) {
    
    $update = Telegram::commandsHandler(true);
    
    $data = json_decode($update,true);
    $messageText = (isset($data['message']['text']) && !empty($data['message']['text']))?$data['message']['text']:'';
    
    file_put_contents(public_path().'/updates.txt',$update.'>>'.$token);
    
    $telegram = new Api($token);
    $response = $telegram->getMe();
    
	$botId = $response->getId();
    $chatId = $data['message']['chat']['id'];
    $message_id = $data['message']['message_id'];
    
    $bot_data = DB::table('bots')->where('bot_token', 'LIKE', '%'.$token.'%')->get();
    $dbBotId = (isset($bot_data[0]->id) && $bot_data[0]->id!='')?$bot_data[0]->id:'';
    
    /* Add bot user */
    $from_id = $data['message']['from']['id'];
    $first_name = $data['message']['from']['first_name'];
    $last_name = $data['message']['from']['last_name'];
    
    $bot_user = DB::table('bot_users')
                    ->where('bot_id', '=', $dbBotId)
                    ->where('first_name', 'LIKE', $first_name)
                    ->get();
    
    $bot_user_id = '';
    if(isset($bot_user[0]->id) && !empty($bot_user[0]->id)){
        $bot_user_id = $bot_user[0]->id;
    }
    else{
        $bot_user_id = DB::table('bot_users')->insertGetId(
                ['bot_id' => $dbBotId, 'first_name' => $first_name, 'last_name' => $last_name, 'username' => '', 'fromid' => $from_id, 'created_at' => date('Y-m-d h:i:s'), 'modified_at' => date('Y-m-d h:i:s')]
            );
        
        //file_put_contents(public_path().'/result.txt',$bot_user_id);
    }
    /*******************************************************/
    
    
    
    /* Bot Message */
    if(!empty($bot_user_id)){
        
        //$date = $data['message']['date'];
        $bot_msg_date = date('Y-m-d h:i:s');
        
        $bot_messages_id = DB::table('bot_messages')->insertGetId(
                ['bot_id' => $dbBotId,'bot_user_id' => $bot_user_id,'date' => $bot_msg_date,'forward_from' => $from_id, 'forward_from_chat' => $chatId, 'forward_date' => $bot_msg_date, 'reply_to_chat' => '', 'reply_to_message' => '', 'text' => $messageText]
            );
    }    
    /*******************************************************/
    
    
    
    /*
    DB::table('tmp_bots')->insert(
        ['data_value' => serialize($bot_data)]
    );
    */
    
    
    
    
    if(!empty($dbBotId)){
        
        $autoresponse = '';
        if(isset($bot_data[0]->autoresponse) && !empty($bot_data[0]->autoresponse)){
            $autoresponse = $bot_data[0]->autoresponse;
        }
        
        $contact_form = '';
        if(isset($bot_data[0]->contact_form) && !empty($bot_data[0]->contact_form)){
            $contact_form = $bot_data[0]->contact_form;
        }
        
        $galleries = '';
        if(isset($bot_data[0]->galleries) && !empty($bot_data[0]->galleries)){
            $galleries = $bot_data[0]->galleries;
        }
        
        $channels = '';
        if(isset($bot_data[0]->channels) && !empty($bot_data[0]->channels)){
            $channels = $bot_data[0]->channels;
        }
        
        $array = array(
                '0' => $autoresponse,
                '1' => $contact_form,
                '2' => $galleries,
                '3' => $channels
        );
        
        $ke_arr = '';
        for($i = 0; $i<=3;$i++){
            if(isset($array[$i]) && !empty($array[$i])){
                $ke_arr[$i] = $array[$i];
            }
        }

        $ke_arr = array_chunk($ke_arr,2);
        $keyboard = $ke_arr;
		$msg = (isset($bot_data[0]->start_message) && !empty($bot_data[0]->start_message))?$bot_data[0]->start_message:'';
        

app/Models/FrontUser.php
<?php 

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class FrontUser extends Model{
	protected $table = 'users';
}

resources/views/front/front_user/change_password.blade.php
@extends('front.template')
@section('main')



    <div class="col-sm-8 col-sm-offset-4 col-lg-9 col-lg-offset-3">
     
      @include('front.top')  
      
      {!! Form::open(['url' => 'front_user/change_password', 'method' => 'post','enctype'=>"multipart/form-data", 'class' => 'form-horizontal panel','id' =>'','onsubmit' => 'return passwordValidate();']) !!}
      
      {!! Form::hidden('id', $user['id'], array('id' => 'idd','value' =>$user['id'] )) !!}
      
    
      
        <div id="row2">
          <div class="my_account telegram">
            <h4>{!! HTML::image('img/front/telegrtam_icon.png') !!}<span>{{ trans('front/fornt_user.telegram') }}</span></h4>
            <h5>{{ trans('front/fornt_user.update_pass') }}</h5>
          </div>
          
          <div class="buying">
              <div class="create_bot">
                
                <div class="crete_bot_form">
                  <ul>
                    <li>
                      <span>{{ trans('front/fornt_user.new_password') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label id="new_pass">{!! Form::control('password', 0, 'new_password', $errors,'','') !!}</label>
                    </li>
                    
                    <li>
                      <span>{{ trans('front/fornt_user.confirm_password') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label id="cpass">{!! Form::control('password', 0, 'confirm_password', $errors,'',''	) !!}</label>
                    </li>
			            
                  </ul>
                
                </div>
                
               <div class="submit">
                  {!! Form::submit_new(trans('front/form.send')) !!}
                </div>
                
            </div>
        </div>
      </div>
      
      
      
    
      {!! Form::close() !!}
      
  </div>

<script>
  function passwordValidate(){
    var new_password = $('#new_password').val();
    var confirm_password = $('#confirm_password').val();
    var chk = true;
    if(new_password == ''){
      chk = false;
      $('#new_pass .form-group').addClass('has-error');
    }
    else{
      $('#new_pass .form-group').removeClass('has-error');
    }
    
    if(confirm_password == ''){
      chk = false;
      $('#cpass .form-group').addClass('has-error');
    }
    else{
      $('#cpass .form-group').removeClass('has-error');
    }
    
    if(new_password != confirm_password){
      chk = false;
      $('#cpass .form-group').addClass('has-error');
    }
    
    if(chk){
      return true;
    }
    else{
      return false;
    }
    
  }
</script>

@stop

resources/views/front/front_user/edit.blade.php
@extends('front.template')
@section('main')


    <div class="col-sm-8 col-sm-offset-4 col-lg-9 col-lg-offset-3">
     
      @include('front.top')  
      
      {!! Form::open(['url' => 'front_user/update', 'method' => 'post','enctype'=>"multipart/form-data", 'class' => 'form-horizontal panel','id' =>'','onsubmit' => 'return passwordValidate();']) !!}
      
      {!! Form::hidden('id', $user['id'], array('id' => 'idd','value' =>$user['id'] )) !!}
      
    
      
        <div id="row2">
          <div class="my_account telegram">
            <h4>{!! HTML::image('img/front/telegrtam_icon.png') !!}<span>{{ trans('front/fornt_user.telegram') }}</span></h4>
            <h5>{{ trans('front/fornt_user.create') }}</h5>
          </div>
          
          <div class="buying">
              <div class="create_bot">
                
                <div class="crete_bot_form">
					<?php
						$fname = (isset($user['first_name']) && !empty($user['first_name'])?$user['first_name']:'');
                        $lname = (isset($user['last_name']) && !empty($user['last_name'])?$user['last_name']:'');
                        $email = (isset($user['email']) && !empty($user['email'])?$user['email']:'');
                        $country_id = (isset($user['country_id']) && !empty($user['country_id'])?$user['country_id']:'');
                        $zipcode = (isset($user['zipcode']) && !empty($user['zipcode'])?$user['zipcode']:'');
                        $mobile = (isset($user['mobile']) && !empty($user['mobile'])?$user['mobile']:'');

					?>	
                  <ul>
                    <li>
                      <span>{{ trans('front/fornt_user.first_name') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label id="uName">{!! Form::control('text', 0, 'first_name', $errors,'',$fname) !!}</label>
                    </li>
                    
                    <li>
                      <span>{{ trans('front/fornt_user.last_name') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label id="aToken">{!! Form::control('text', 0, 'last_name', $errors,'',$lname	) !!}</label>
                    </li>
					
					<li>
                      <span>{{ trans('front/fornt_user.email') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label>{!! Form::control_stripe_email('text', 0, 'email', $errors,'',$email) !!}</label>
                    </li>  
                    
					  
                    <li>
                      <span>{{ trans('front/fornt_user.user_image') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label>{!! Form::control('file', 0, 'image', $errors) !!}<span>{{ trans('front/fornt_user.browse') }}</span></label>
                    </li>
					  
					<li>
						<span>{{ trans('front/fornt_user.country') }} {!! HTML::image('img/front/icon.png') !!}</span>
						<label>
							<select id="country" name="country" class="form-control">
								<option value=""></option>
							   <?php
								   if(!empty($country)){
										foreach($country as $k1 => $v1){
											$cls = '';
											if($country_id == $v1->id){
												$cls = 'selected="selected"';
											}
											echo '<option '.$cls.' value="'.$v1->id.'">'.$v1->name.'</option>';
										}
								   }     
							   ?>
							</select>
						</label>
					</li>  
					  
					<li>
                      <span>{{ trans('front/fornt_user.zipcode') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label>{!! Form::control('text', 0, 'zipcode', $errors,'',$zipcode) !!}</label>
                    </li>
					  
					<li>
                      <span>{{ trans('front/fornt_user.mobile') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label>{!! Form::control('text', 0, 'mobile', $errors,'',$mobile) !!}</label>
                    </li>  
                    
                    
           <li>
                      <span>{{ trans('front/fornt_user.new_password') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label id="new_pass">{!! Form::control('password', 0, 'new_password', $errors,'','') !!}</label>
                    </li>
                    
                    <li>
                      <span>{{ trans('front/fornt_user.confirm_password') }} {!! HTML::image('img/front/icon.png') !!}</span>
                      <label id="cpass">{!! Form::control('password', 0, 'confirm_password', $errors,'',''	) !!}</label>
                    </li>
                    
                  
                  </ul>
                
                </div>
                
               <div class="submit">
                  {!! Form::submit_new(trans('front/form.send')) !!}
                </div>
                
            </div>
        </div>
      </div>
      
      
      
    
      {!! Form::close() !!}
      
  </div>

<script>
  function passwordValidate(){
    var new_password = $('#new_password').val();
    var confirm_password = $('#confirm_password').val();
    var chk = true;
    
    if(new_password != '')
    {
      if(confirm_password == '')
      {
        chk = false;
        $('#cpass .form-group').addClass('has-error');
      }
      else{
        $('#cpass .form-group').removeClass('has-error');
      }

      if(new_password != confirm_password){
        chk = false;
        $('#cpass .form-group').addClass('has-error');
      }

      if(chk){
        return true;
      }
      else{
        return false;
      }
    }

  }
</script>

@stop

resources/views/front/front_user/index.blade.php
@extends('front.template')
@section('main')

<!-- http://jlinn.github.io/stripe-api-php/api/subscriptions.html -->

{!! HTML::script('js/front/paging.js') !!}

    <div class="col-sm-8 col-sm-offset-4 col-lg-9 col-lg-offset-3">
     
      @include('front.top')  
      
      <div class="my_account">
        <h4>{!! trans('front/fornt_user.my_account') !!}</h4>
        <div class="modify_icon">
          {!! link_to_route_img('front_user.edit', "<span>".trans('front/fornt_user.modify_account')."</span>".HTML::image('img/front/modify_icon.png'), [Auth::user()->id], ['class' => '']) !!}
        </div>
      </div>
      
      <div class="col-lg-7"><div class="col-my-bots">
        <h5>{{ trans('front/fornt_user.my_bots') }}</h5>
        
        <div class="bots_content" id="">
        <table id="bots_content">
        	<tr><td></td></tr>
        <?php
          if(!empty($data)){
            foreach($data as $d1 => $dv1){
              ?>
              <tr>
              <td>
                <h6><a href="{!! URL::to('/bot/detail/'.$dv1['bot']['id']) !!}"><?php echo $dv1['bot']['username'];?></a></h6>
                <ul>
                  <li>
                    <p><?php echo $dv1['user_subscription']['Plan']['name'];?></p>
                    <!--<a href="{!! URL::to('/bot/destroy/'.$dv1['bot']['id']) !!}" onclick="return confirm('Are you sure want to delete this bot?');"><span aria-hidden="true" class="glyphicon glyphicon-trash"></span></a>-->
                    <a href="#" onclick="return confirm('Are you sure want to delete this bot?');"><span aria-hidden="true" class="glyphicon glyphicon-trash"></span></a>
                  </li>

                  <li><p>{{ trans('front/fornt_user.automatic_renewal') }}:<?php echo date('d/m/Y',strtotime($dv1['user_subscription']['expiry_date']));?></p></li>
                </ul>
                </td>
                </tr>
              <?php
            }
          }
          else{
            ?>
          <ul>
            <li>{{ trans('front/fornt_user.no_record_found') }}</li>
          </ul>
            <?php
          }
        ?>
        </table>
        <ul id="bots_contentNavPosition" class="pagination"></ul>
        </div>
        
      
        <h5>{{ trans('front/fornt_user.my_channel') }}</h5>
        <h5>{!! link_to_route('my_channel.create', '+', [], ['class' => '']) !!}</h5>
        
        <div class="bots_content">
        	<table id="channel_content">
        	<tr><td></td></tr>
          <?php
            if(!empty($chanel_data)){
              foreach($chanel_data as $ck1 => $cv1){
                ?>
                	<tr>
                    <td>
                  <h6><?php echo $cv1['channel']['name'];?></h6>
                  <ul>
                    <li>
                      <p></p>
                      <a href="#"><span aria-hidden="true" class="glyphicon glyphicon-trash"></span></a>
                    </li>
                    <li><p>{{ trans('front/fornt_user.automatic_renewal') }}:<?php echo date('d/m/Y',strtotime($cv1['user_subscription']['expiry_date']));?></p></li>
                </ul>
                </td>
                </tr>
                <?php
              }
            }
          else{
            ?>
          <ul>
            <li>{{ trans('front/fornt_user.no_record_found') }}</li>
          </ul>
            <?php
          }
          ?>
          </table>
          <ul id="channel_contentNavPosition" class="pagination"></ul>
        </div>
        
        </div>
      </div>
      
      <div class="col-lg-5">
        <div class="col-plan">
          <h2>{{ trans('front/fornt_user.plan_subscription') }}</h2>
          <table id="bot_plan_sub">
            <thead>
              <tr>
                <th>{{ trans('front/fornt_user.bots') }}</th>
                <th>{{ trans('front/fornt_user.plan') }} </th>
                <th>{{ trans('front/fornt_user.cost') }} </th>
                <th>{{ trans('front/fornt_user.status') }}</th>
              </tr>
            </thead>
            <tbody>
              <?php
                if(!empty($data)){
                  foreach($data as $d2 => $v2){
                    ?>
                        <tr>
                          <td><?php echo $v2['bot']['username'];?></td>
                          <td><?php echo $v2['user_subscription']['Plan']['name'];?></td>
                          <td><?php echo '€'.$v2['user_subscription']['price'];?></td>
                          <td><?php echo $v2['user_subscription']['status'];?></td>
                        </tr>
                    <?php
                  }
                }
                else{
                  ?>
                    <tr>
                      <td colspan="4">{{ trans('front/fornt_user.no_record') }}</td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
          </table>
          <ul id="bot_plan_subNavPosition" class="pagination"></ul>
        </div>
        
        <div class="col-plan">
          <h2>{{ trans('front/fornt_user.billing_transactions') }}</h2>
          <table id="bot_billing">
            <thead>
              <tr>
                <th>{{ trans('front/fornt_user.transaction_date') }}</th>
                <th>{{ trans('front/fornt_user.description') }} </th>
                <th>{{ trans('front/fornt_user.type') }} </th>
                <th>{{ trans('front/fornt_user.amount') }}</th>
              </tr>
            </thead>
            <tbody>
              <?php
                if(!empty($transactions)){
                  foreach($transactions as $t1 => $t2){
                    ?>
                        <tr>
                          <td><?php echo $t2->created_at;?></td>
                          <td><?php echo $t2->Description;?></td>
                          <td><?php echo $t2->types;?></td>
                          <td><?php echo '€'.$t2->amount;?></td>
                        </tr>
                    <?php
                  }
                }
                else{
                  ?>
                    <tr>
                      <td colspan="4">{{ trans('front/fornt_user.no_record') }}</td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
          </table>
          <ul id="bot_billingNavPosition" class="pagination"></ul>
        </div>
        
        <!------------ Channel ------------------->
         <div class="col-plan">
          <h2>{{ trans('front/fornt_user.chanel_plan_subscription') }}</h2>
          <table id="channel_plans">
            <thead>
              <tr>
                <th>{{ trans('front/fornt_user.channels') }}</th>
                <th>{{ trans('front/fornt_user.plan') }} </th>
                <th>{{ trans('front/fornt_user.cost') }} </th>
                <th>{{ trans('front/fornt_user.status') }}</th>
              </tr>
            </thead>
            <tbody>
              <?php
                if(!empty($chanel_data)){
                  foreach($chanel_data as $c2 => $cv2){
                    ?>
                        <tr>
                          <td><?php echo $cv2['channel']['name'];?></td>
                          <td><?php echo $cv2['user_subscription']['Plan']['name'];?></td>
                          <td><?php echo '€'.$cv2['user_subscription']['price'];?></td>
                          <td><?php echo $cv2['user_subscription']['status'];?></td>
                        </tr>
                    <?php
                  }
                }
                else{
                  ?>
                    <tr>
                      <td colspan="4">{{ trans('front/fornt_user.no_record') }}</td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
          </table>
          <ul id="channel_plansNavPosition" class="pagination"></ul>
        </div>
        
        <div class="col-plan">
          <h2>{{ trans('front/fornt_user.chanel_billing_transactions') }}</h2>
          <table id="channel_billing">
            <thead>
              <tr>
                <th>{{ trans('front/fornt_user.transaction_date') }}</th>
                <th>{{ trans('front/fornt_user.description') }} </th>
                <th>{{ trans('front/fornt_user.type') }} </th>
                <th>{{ trans('front/fornt_user.amount') }}</th>
              </tr>
            </thead>
            <tbody>
              <?php
                if(!empty($chanel_transactions)){
                  foreach($chanel_transactions as $ct1 => $ct2){
                    ?>
                        <tr>
                          <td><?php echo $ct2->created_at;?></td>
                          <td><?php echo $ct2->Description;?></td>
                          <td><?php echo $ct2->types;?></td>
                          <td><?php echo '€'.$ct2->amount;?></td>
                        </tr>
                    <?php
                  }
                }
                else{
                  ?>
                    <tr>
                      <td colspan="4">{{ trans('front/fornt_user.no_record') }}</td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
          </table>
          <ul id="channel_billingNavPosition" class="pagination"></ul>
        </div>
        <!----------------------------------------->
        
</div>
      
  </div>
  
  
  <script type="text/javascript"><!--

  	var pager_bots_content = new Pager('bots_content', 2); 
	pager_bots_content.init(); 
	pager_bots_content.showPageNav('pager_bots_content', 'bots_contentNavPosition'); 
	pager_bots_content.showPage('pager_bots_content',1);
	
	var pager_channel_content = new Pager('channel_content', 2); 
	pager_channel_content.init(); 
	pager_channel_content.showPageNav('pager_channel_content', 'channel_contentNavPosition'); 
	pager_channel_content.showPage('pager_channel_content',1);
	
	var pager_bot_plan_sub = new Pager('bot_plan_sub', 5); 
	pager_bot_plan_sub.init(); 
	pager_bot_plan_sub.showPageNav('pager_bot_plan_sub', 'bot_plan_subNavPosition'); 
	pager_bot_plan_sub.showPage('pager_bot_plan_sub',1);
	
	
	var pager_bot_billing = new Pager('bot_billing', 5); 
	pager_bot_billing.init(); 
	pager_bot_billing.showPageNav('pager_bot_billing', 'bot_billingNavPosition'); 
	pager_bot_billing.showPage('pager_bot_billing',1);
	
	var pager_channel_plans = new Pager('channel_plans', 5); 
	pager_channel_plans.init(); 
	pager_channel_plans.showPageNav('pager_channel_plans', 'channel_plansNavPosition'); 
	pager_channel_plans.showPage('pager_channel_plans',1);
	
	var pager_channel_billing = new Pager('channel_billing', 5); 
	pager_channel_billing.init(); 
	pager_channel_billing.showPageNav('pager_channel_billing', 'channel_billingNavPosition'); 
	pager_channel_billing.showPage('pager_channel_billing',1);
	
    //-->
  </script>
  
@stop